service: "cmr-${self:custom.cmrStacName}-api"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  role: cmrStacRole
  deploymentBucket: ${cf:${opt:stage}.cmrStacDeploymentBucket}
  vpc:
    securityGroupIds:
      - ${cf:${opt:stage}.servicesSecurityGroupId}
    subnetIds: !Split [ ",", "${cf:${opt:stage}.subnetIds}" ]
custom:
  cmrStacName: ${opt:cmr-stac-name}
  cmrStacRelativeRootUrl: ${opt:cmr-stac-relative-root-url, '/stac'}
  docsBucket: cmr-stac-static-bucket-${opt:stage}
  assets:
    targets:
      - bucket:
          Ref: cmrStacDocsBucket
        empty: true
        prefix: docs
        files:
          - source: ./docs/
            globs: '**/index.html'

functions:
  search-api:
    name: cmr-${self:custom.cmrStacName}-${opt:stage}
    handler: lib/application.handler
    timeout: 6
    events:
      - alb:
          listenerArn: ${cf:${opt:stage}.servicesLbListenerArn}
          priority: ${opt:cmr-lb-priority, 83}
          conditions:
            path: ${self:custom.cmrStacRelativeRootUrl}*
    environment:
      CMR_SEARCH_HOST: cmr.earthdata.nasa.gov/search
      CMR_PROVIDER_HOST: cmr.earthdata.nasa.gov/ingest/providers
      CMR_SEARCH_PROTOCOL: https
      CMR_STAC_RELATIVE_ROOT_URL: /stac
      BROWSE_PATH: year/month/day
      LOG_DISABLED: false
      LOG_LEVEL: debug
      STAC_VERSION: 1.0.0-beta.2

resources:
  Resources:
    cmrStacRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: cmrStacRole-${self:custom.cmrStacName}-${opt:stage}
        PermissionsBoundary: arn:aws:iam::#{AWS::AccountId}:policy/NGAPShRoleBoundary
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
    cmrStacDocsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.docsBucket}

plugins:
  - serverless-pseudo-parameters
  - serverless-s3-deploy
